CREATE TABLE IF NOT EXISTS "Catalogs"(
  "id" SERIAL PRIMARY KEY,
  "name" VARCHAR(64) NOT NULL CHECK(name != ''),
  "userId" NUMBER NOT NULL REFERENCES "Users" ("id") ON DELETE CASCADE,
  "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
);
CREATE TABLE IF NOT EXISTS "Conversations"(
  "id" BIGSERIAL PRIMARY KEY,
  "cusomerId" NUMBER NOT NULL REFERENCES "Users" ("id") ON DELETE CASCADE,
  "creatorId" NUMBER NOT NULL REFERENCES "Users" ("id") ON DELETE CASCADE,
  "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "ConversationsToCatalogs"(
  "conversationId" BIGINT NOT NULL REFERENCES "Conversations" ("id") ON DELETE CASCADE,
  "catalogId" INTEGER NOT NULL REFERENCES "Catalogs"("id") ON DELETE CASCADE,
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("conversationId", "catalogId"),
);
CREATE TABLE IF NOT EXISTS "Messages"(
  "id" BIGSERIAL PRIMARY KEY,
  "userId" INTEGER NOT NULL REFERENCES "Users" ("id") ON DELETE CASCADE,
  "body" VARCHAR(128) NOT NULL CHECK("body" != ''),
  "conversationId" BIGINT NOT NULL REFERENCES "Conversations" ("id") ON DELETE CASCADE,
  "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "BlackLists"(
  "userId" NUMBER NOT NULL REFERENCES "Users" ("id") ON DELETE CASCADE,
  "blockedUserId" NUMBER NOT NULL REFERENCES "Users" ("id") ON DELETE CASCADE,
  "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "BlackLists"(
  "userId" NUMBER NOT NULL REFERENCES "Users" ("id") ON DELETE CASCADE,
  "blockedUserId" NUMBER NOT NULL REFERENCES "Users" ("id") ON DELETE CASCADE,
  "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);